[build]
command = "npm run build"
publish = "public"

[build.environment]
HUGO_VERSION = "0.150.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
NODE_VERSION = "18"

[context.deploy-preview]
command = "npm run generate:banner && hugo --gc --minify --baseURL=$DEPLOY_PRIME_URL"
[context.deploy-preview.environment]
HUGO_ENV = "preview"

[[plugins]]
package = "netlify-plugin-hugo-cache-resources"
