[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.150.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  NODE_VERSION = "18"

[context.production]
  command = "hugo --gc --minify --baseURL=https://devopsdays.ch"

[context.deploy-preview]
  command = "hugo --gc --minify --baseURL=$DEPLOY_PRIME_URL"
  [context.deploy-preview.environment]
    HUGO_ENV = "preview"

[context.branch-deploy]
  command = "hugo --gc --minify --baseURL=$DEPLOY_PRIME_URL"
  [context.branch-deploy.environment]
    HUGO_ENV = "development"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
